# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ruben/robocomp/tools/rcmonitor/headt2pDlg.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_HeadT2PDlg(object):
    def setupUi(self, HeadT2PDlg):
        HeadT2PDlg.setObjectName(_fromUtf8("HeadT2PDlg"))
        HeadT2PDlg.resize(418, 221)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HeadT2PDlg.sizePolicy().hasHeightForWidth())
        HeadT2PDlg.setSizePolicy(sizePolicy)
        HeadT2PDlg.setMaximumSize(QtCore.QSize(4800, 44444))
        self.verticalLayout_3 = QtGui.QVBoxLayout(HeadT2PDlg)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_3 = QtGui.QLabel(HeadT2PDlg)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout.addWidget(self.label_3)
        self.sbLeftPan = QtGui.QDoubleSpinBox(HeadT2PDlg)
        self.sbLeftPan.setMinimum(-3.0)
        self.sbLeftPan.setMaximum(3.0)
        self.sbLeftPan.setSingleStep(0.05)
        self.sbLeftPan.setObjectName(_fromUtf8("sbLeftPan"))
        self.horizontalLayout.addWidget(self.sbLeftPan)
        self.label_5 = QtGui.QLabel(HeadT2PDlg)
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout.addWidget(self.label_5)
        self.lcdLeftPan = QtGui.QLCDNumber(HeadT2PDlg)
        self.lcdLeftPan.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdLeftPan.setObjectName(_fromUtf8("lcdLeftPan"))
        self.horizontalLayout.addWidget(self.lcdLeftPan)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(HeadT2PDlg)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.sbRightPan = QtGui.QDoubleSpinBox(HeadT2PDlg)
        self.sbRightPan.setMinimum(-3.0)
        self.sbRightPan.setMaximum(3.0)
        self.sbRightPan.setSingleStep(0.05)
        self.sbRightPan.setObjectName(_fromUtf8("sbRightPan"))
        self.horizontalLayout_2.addWidget(self.sbRightPan)
        self.lcdRightPan = QtGui.QLCDNumber(HeadT2PDlg)
        self.lcdRightPan.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdRightPan.setObjectName(_fromUtf8("lcdRightPan"))
        self.horizontalLayout_2.addWidget(self.lcdRightPan)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 1, 1, 1)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem = QtGui.QSpacerItem(40, 28, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.dbTilt = QtGui.QLabel(HeadT2PDlg)
        self.dbTilt.setObjectName(_fromUtf8("dbTilt"))
        self.horizontalLayout_3.addWidget(self.dbTilt)
        self.sbTilt = QtGui.QDoubleSpinBox(HeadT2PDlg)
        self.sbTilt.setMinimum(-3.0)
        self.sbTilt.setMaximum(3.0)
        self.sbTilt.setSingleStep(0.05)
        self.sbTilt.setObjectName(_fromUtf8("sbTilt"))
        self.horizontalLayout_3.addWidget(self.sbTilt)
        self.lcdTilt = QtGui.QLCDNumber(HeadT2PDlg)
        self.lcdTilt.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdTilt.setObjectName(_fromUtf8("lcdTilt"))
        self.horizontalLayout_3.addWidget(self.lcdTilt)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pbSaccadic2DLeft = QtGui.QPushButton(HeadT2PDlg)
        self.pbSaccadic2DLeft.setObjectName(_fromUtf8("pbSaccadic2DLeft"))
        self.horizontalLayout_7.addWidget(self.pbSaccadic2DLeft)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem4)
        self.pbSaccadic2DRight = QtGui.QPushButton(HeadT2PDlg)
        self.pbSaccadic2DRight.setObjectName(_fromUtf8("pbSaccadic2DRight"))
        self.horizontalLayout_8.addWidget(self.pbSaccadic2DRight)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.pbSaccadic3D = QtGui.QPushButton(HeadT2PDlg)
        self.pbSaccadic3D.setObjectName(_fromUtf8("pbSaccadic3D"))
        self.horizontalLayout_9.addWidget(self.pbSaccadic3D)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem8)
        self.pbReset = QtGui.QPushButton(HeadT2PDlg)
        self.pbReset.setObjectName(_fromUtf8("pbReset"))
        self.horizontalLayout_11.addWidget(self.pbReset)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(HeadT2PDlg)
        QtCore.QMetaObject.connectSlotsByName(HeadT2PDlg)

    def retranslateUi(self, HeadT2PDlg):
        HeadT2PDlg.setWindowTitle(_translate("HeadT2PDlg", "HeadNTP Controller", None))
        self.label_3.setText(_translate("HeadT2PDlg", "Left Pan", None))
        self.label_4.setText(_translate("HeadT2PDlg", "Right Pan", None))
        self.dbTilt.setText(_translate("HeadT2PDlg", "Tilt   ", None))
        self.pbSaccadic2DLeft.setText(_translate("HeadT2PDlg", "Saccadic 2D Left", None))
        self.pbSaccadic2DRight.setText(_translate("HeadT2PDlg", "Saccadic 2D Right", None))
        self.pbSaccadic3D.setText(_translate("HeadT2PDlg", "Saccadic 3D", None))
        self.pbReset.setText(_translate("HeadT2PDlg", "Reset", None))

