# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ruben/robocomp/tools/rcmonitor/openA.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_OpenA(object):
    def setupUi(self, OpenA):
        OpenA.setObjectName(_fromUtf8("OpenA"))
        OpenA.resize(827, 365)
        self.verticalLayout_3 = QtGui.QVBoxLayout(OpenA)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(OpenA)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.sliceBox = QtGui.QGroupBox(self.tab1)
        self.sliceBox.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliceBox.sizePolicy().hasHeightForWidth())
        self.sliceBox.setSizePolicy(sizePolicy)
        self.sliceBox.setMinimumSize(QtCore.QSize(0, 170))
        self.sliceBox.setObjectName(_fromUtf8("sliceBox"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.sliceBox)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 591, 141))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gl1 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gl1.setObjectName(_fromUtf8("gl1"))
        self.slicePathWidget = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(15)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slicePathWidget.sizePolicy().hasHeightForWidth())
        self.slicePathWidget.setSizePolicy(sizePolicy)
        self.slicePathWidget.setText(_fromUtf8(""))
        self.slicePathWidget.setReadOnly(True)
        self.slicePathWidget.setObjectName(_fromUtf8("slicePathWidget"))
        self.gl1.addWidget(self.slicePathWidget, 1, 2, 1, 1)
        self.button = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.button.setObjectName(_fromUtf8("button"))
        self.gl1.addWidget(self.button, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gl1.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.gl1.addItem(spacerItem, 1, 1, 1, 1)
        self.sliceOpts = QtGui.QTextEdit(self.gridLayoutWidget_2)
        self.sliceOpts.setObjectName(_fromUtf8("sliceOpts"))
        self.gl1.addWidget(self.sliceOpts, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.sliceBox)
        spacerItem1 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.endpointBox = QtGui.QGroupBox(self.tab1)
        self.endpointBox.setMinimumSize(QtCore.QSize(0, 50))
        self.endpointBox.setObjectName(_fromUtf8("endpointBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.endpointBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.hl2 = QtGui.QHBoxLayout()
        self.hl2.setObjectName(_fromUtf8("hl2"))
        self.endpointName = QtGui.QLineEdit(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endpointName.sizePolicy().hasHeightForWidth())
        self.endpointName.setSizePolicy(sizePolicy)
        self.endpointName.setText(_fromUtf8(""))
        self.endpointName.setObjectName(_fromUtf8("endpointName"))
        self.hl2.addWidget(self.endpointName)
        spacerItem2 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.hl2.addItem(spacerItem2)
        self.endpointProtocol = QtGui.QComboBox(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endpointProtocol.sizePolicy().hasHeightForWidth())
        self.endpointProtocol.setSizePolicy(sizePolicy)
        self.endpointProtocol.setObjectName(_fromUtf8("endpointProtocol"))
        self.endpointProtocol.addItem(_fromUtf8(""))
        self.endpointProtocol.addItem(_fromUtf8(""))
        self.hl2.addWidget(self.endpointProtocol)
        spacerItem3 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.hl2.addItem(spacerItem3)
        self.label = QtGui.QLabel(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.hl2.addWidget(self.label)
        spacerItem4 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hl2.addItem(spacerItem4)
        self.endpointPort = QtGui.QSpinBox(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.endpointPort.sizePolicy().hasHeightForWidth())
        self.endpointPort.setSizePolicy(sizePolicy)
        self.endpointPort.setMinimumSize(QtCore.QSize(60, 0))
        self.endpointPort.setMaximum(65535)
        self.endpointPort.setProperty("value", 10001)
        self.endpointPort.setObjectName(_fromUtf8("endpointPort"))
        self.hl2.addWidget(self.endpointPort)
        spacerItem5 = QtGui.QSpacerItem(15, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.hl2.addItem(spacerItem5)
        self.label_6 = QtGui.QLabel(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.hl2.addWidget(self.label_6)
        self.hostName = QtGui.QLineEdit(self.endpointBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostName.sizePolicy().hasHeightForWidth())
        self.hostName.setSizePolicy(sizePolicy)
        self.hostName.setObjectName(_fromUtf8("hostName"))
        self.hl2.addWidget(self.hostName)
        self.horizontalLayout.addLayout(self.hl2)
        self.verticalLayout.addWidget(self.endpointBox)
        spacerItem6 = QtGui.QSpacerItem(20, 1, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem6)
        self.buttonBox1 = QtGui.QDialogButtonBox(self.tab1)
        self.buttonBox1.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox1.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox1.setObjectName(_fromUtf8("buttonBox1"))
        self.verticalLayout.addWidget(self.buttonBox1)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_3 = QtGui.QLabel(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.buttonBox2 = QtGui.QDialogButtonBox(self.tab2)
        self.buttonBox2.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox2.setObjectName(_fromUtf8("buttonBox2"))
        self.gridLayout.addWidget(self.buttonBox2, 3, 2, 1, 1)
        self.methodsText = QtGui.QPlainTextEdit(self.tab2)
        self.methodsText.setMaximumSize(QtCore.QSize(290, 16777215))
        self.methodsText.setFrameShape(QtGui.QFrame.NoFrame)
        self.methodsText.setFrameShadow(QtGui.QFrame.Plain)
        self.methodsText.setLineWidth(0)
        self.methodsText.setUndoRedoEnabled(False)
        self.methodsText.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.methodsText.setReadOnly(True)
        self.methodsText.setPlainText(_fromUtf8(""))
        self.methodsText.setObjectName(_fromUtf8("methodsText"))
        self.gridLayout.addWidget(self.methodsText, 2, 1, 1, 1)
        self.symbolsText = QtGui.QPlainTextEdit(self.tab2)
        self.symbolsText.setMaximumSize(QtCore.QSize(290, 16777215))
        self.symbolsText.setFrameShape(QtGui.QFrame.NoFrame)
        self.symbolsText.setFrameShadow(QtGui.QFrame.Plain)
        self.symbolsText.setLineWidth(0)
        self.symbolsText.setUndoRedoEnabled(False)
        self.symbolsText.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.symbolsText.setReadOnly(True)
        self.symbolsText.setPlainText(_fromUtf8(""))
        self.symbolsText.setObjectName(_fromUtf8("symbolsText"))
        self.gridLayout.addWidget(self.symbolsText, 2, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout.addWidget(self.textEdit, 2, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)

        self.retranslateUi(OpenA)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OpenA)

    def retranslateUi(self, OpenA):
        OpenA.setWindowTitle(_translate("OpenA", "Open connection", None))
        self.sliceBox.setTitle(_translate("OpenA", "Slice Parameters", None))
        self.button.setText(_translate("OpenA", "Select file", None))
        self.label_2.setText(_translate("OpenA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Slice paths</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(one directory per line)</p></body></html>", None))
        self.endpointBox.setTitle(_translate("OpenA", "ICE Endpoint", None))
        self.endpointProtocol.setItemText(0, _translate("OpenA", "tcp", None))
        self.endpointProtocol.setItemText(1, _translate("OpenA", "udp", None))
        self.label.setText(_translate("OpenA", "-p", None))
        self.label_6.setText(_translate("OpenA", "-h", None))
        self.hostName.setText(_translate("OpenA", "localhost", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("OpenA", "Tab 1", None))
        self.label_3.setText(_translate("OpenA", "Symbols", None))
        self.label_4.setText(_translate("OpenA", "Code", None))
        self.label_5.setText(_translate("OpenA", "Remote methods", None))
        self.textEdit.setHtml(_translate("OpenA", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Write code here or select a template from menu.</p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("OpenA", "Tab 2", None))

