# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ruben/robocomp/tools/rcmanager/formManager.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(387, 518)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(200, 250))
        self.verticalLayout_4 = QtGui.QVBoxLayout(Form)
        self.verticalLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.tabWidget = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.listTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.listTab.sizePolicy().hasHeightForWidth())
        self.listTab.setSizePolicy(sizePolicy)
        self.listTab.setObjectName(_fromUtf8("listTab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.listTab)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkList = QtGui.QListWidget(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.checkList.sizePolicy().hasHeightForWidth())
        self.checkList.setSizePolicy(sizePolicy)
        self.checkList.setObjectName(_fromUtf8("checkList"))
        self.verticalLayout.addWidget(self.checkList)
        self.formLayout_7 = QtGui.QFormLayout()
        self.formLayout_7.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_7.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_7.setObjectName(_fromUtf8("formLayout_7"))
        self.formLayout_6 = QtGui.QFormLayout()
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.label_3 = QtGui.QLabel(self.listTab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.downButton = QtGui.QPushButton(self.listTab)
        self.downButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../opt/robocomp/share/rcmanager/down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downButton.setIcon(icon)
        self.downButton.setObjectName(_fromUtf8("downButton"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.downButton)
        self.formLayout_7.setLayout(0, QtGui.QFormLayout.LabelRole, self.formLayout_6)
        self.downEdit = QtGui.QLabel(self.listTab)
        self.downEdit.setObjectName(_fromUtf8("downEdit"))
        self.formLayout_7.setWidget(0, QtGui.QFormLayout.FieldRole, self.downEdit)
        self.verticalLayout.addLayout(self.formLayout_7)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.cfgEdit = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cfgEdit.sizePolicy().hasHeightForWidth())
        self.cfgEdit.setSizePolicy(sizePolicy)
        self.cfgEdit.setObjectName(_fromUtf8("cfgEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cfgEdit)
        self.verticalLayout.addLayout(self.formLayout_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_4 = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.wdEdit = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdEdit.sizePolicy().hasHeightForWidth())
        self.wdEdit.setSizePolicy(sizePolicy)
        self.wdEdit.setObjectName(_fromUtf8("wdEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.wdEdit)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_2 = QtGui.QLabel(self.listTab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.upButton = QtGui.QPushButton(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upButton.sizePolicy().hasHeightForWidth())
        self.upButton.setSizePolicy(sizePolicy)
        self.upButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../../../../../../../../../opt/robocomp/share/rcmanager/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upButton.setIcon(icon1)
        self.upButton.setObjectName(_fromUtf8("upButton"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.upButton)
        self.formLayout_5.setLayout(0, QtGui.QFormLayout.LabelRole, self.formLayout_4)
        self.upEdit = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upEdit.sizePolicy().hasHeightForWidth())
        self.upEdit.setSizePolicy(sizePolicy)
        self.upEdit.setObjectName(_fromUtf8("upEdit"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.upEdit)
        self.verticalLayout.addLayout(self.formLayout_5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.listTab)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.checkEdit = QtGui.QLabel(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkEdit.sizePolicy().hasHeightForWidth())
        self.checkEdit.setSizePolicy(sizePolicy)
        self.checkEdit.setObjectName(_fromUtf8("checkEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkEdit)
        self.verticalLayout.addLayout(self.formLayout)
        self.outputText = QtGui.QTextEdit(self.listTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.outputText.sizePolicy().hasHeightForWidth())
        self.outputText.setSizePolicy(sizePolicy)
        self.outputText.setTabChangesFocus(True)
        self.outputText.setUndoRedoEnabled(False)
        self.outputText.setReadOnly(True)
        self.outputText.setObjectName(_fromUtf8("outputText"))
        self.verticalLayout.addWidget(self.outputText)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.listTab, _fromUtf8(""))
        self.graphTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.graphTab.sizePolicy().hasHeightForWidth())
        self.graphTab.setSizePolicy(sizePolicy)
        self.graphTab.setObjectName(_fromUtf8("graphTab"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.graphTab)
        self.verticalLayout_5.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget.addTab(self.graphTab, _fromUtf8(""))
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "RCManager", None))
        self.label_3.setText(_translate("Form", "Comp-down:", None))
        self.downEdit.setText(_translate("Form", "-", None))
        self.label_5.setText(_translate("Form", "Configuration:", None))
        self.cfgEdit.setText(_translate("Form", "-", None))
        self.label_4.setText(_translate("Form", "WorkingDir:", None))
        self.wdEdit.setText(_translate("Form", "-", None))
        self.label_2.setText(_translate("Form", "Comp-up:", None))
        self.upEdit.setText(_translate("Form", "-", None))
        self.label.setText(_translate("Form", "Endpoint:", None))
        self.checkEdit.setText(_translate("Form", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.listTab), _translate("Form", "List view", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.graphTab), _translate("Form", "Graph view", None))

