// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `TouchSensor.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <TouchSensor.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompTouchSensor__TouchSensor__getValues_name = "getValues";

}

namespace Ice
{
}
::IceProxy::Ice::Object* ::IceProxy::RoboCompTouchSensor::upCast(::IceProxy::RoboCompTouchSensor::TouchSensor* p) { return p; }

void
::IceProxy::RoboCompTouchSensor::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompTouchSensor::TouchSensor>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompTouchSensor::TouchSensor;
        v->__copyFrom(proxy);
    }
}

::RoboCompTouchSensor::SensorMap
IceProxy::RoboCompTouchSensor::TouchSensor::getValues(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompTouchSensor__TouchSensor__getValues_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompTouchSensor__TouchSensor__getValues_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompTouchSensor::TouchSensor* __del = dynamic_cast< ::IceDelegate::RoboCompTouchSensor::TouchSensor*>(__delBase.get());
            return __del->getValues(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompTouchSensor::TouchSensor::begin_getValues(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompTouchSensor__TouchSensor__getValues_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompTouchSensor__TouchSensor__getValues_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompTouchSensor__TouchSensor__getValues_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::RoboCompTouchSensor::SensorMap
IceProxy::RoboCompTouchSensor::TouchSensor::end_getValues(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompTouchSensor__TouchSensor__getValues_name);
    ::RoboCompTouchSensor::SensorMap __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompTouchSensor::TouchSensor::ice_staticId()
{
    return ::RoboCompTouchSensor::TouchSensor::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompTouchSensor::TouchSensor::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompTouchSensor::TouchSensor);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompTouchSensor::TouchSensor::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompTouchSensor::TouchSensor);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompTouchSensor::TouchSensor::__newInstance() const
{
    return new TouchSensor;
}

::RoboCompTouchSensor::SensorMap
IceDelegateM::RoboCompTouchSensor::TouchSensor::getValues(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompTouchSensor__TouchSensor__getValues_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    ::RoboCompTouchSensor::SensorMap __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::RoboCompTouchSensor::SensorMap
IceDelegateD::RoboCompTouchSensor::TouchSensor::getValues(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::RoboCompTouchSensor::SensorMap& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompTouchSensor::TouchSensor* servant = dynamic_cast< ::RoboCompTouchSensor::TouchSensor*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->getValues(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::RoboCompTouchSensor::SensorMap& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompTouchSensor__TouchSensor__getValues_name, ::Ice::Normal, __context);
    ::RoboCompTouchSensor::SensorMap __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompTouchSensor::upCast(::RoboCompTouchSensor::TouchSensor* p) { return p; }

namespace
{
const ::std::string __RoboCompTouchSensor__TouchSensor_ids[2] =
{
    "::Ice::Object",
    "::RoboCompTouchSensor::TouchSensor"
};

}

bool
RoboCompTouchSensor::TouchSensor::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompTouchSensor__TouchSensor_ids, __RoboCompTouchSensor__TouchSensor_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompTouchSensor::TouchSensor::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompTouchSensor__TouchSensor_ids[0], &__RoboCompTouchSensor__TouchSensor_ids[2]);
}

const ::std::string&
RoboCompTouchSensor::TouchSensor::ice_id(const ::Ice::Current&) const
{
    return __RoboCompTouchSensor__TouchSensor_ids[1];
}

const ::std::string&
RoboCompTouchSensor::TouchSensor::ice_staticId()
{
    return __RoboCompTouchSensor__TouchSensor_ids[1];
}

::Ice::DispatchStatus
RoboCompTouchSensor::TouchSensor::___getValues(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    ::RoboCompTouchSensor::SensorMap __ret = getValues(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompTouchSensor__TouchSensor_all[] =
{
    "getValues",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

}

::Ice::DispatchStatus
RoboCompTouchSensor::TouchSensor::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompTouchSensor__TouchSensor_all, __RoboCompTouchSensor__TouchSensor_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompTouchSensor__TouchSensor_all)
    {
        case 0:
        {
            return ___getValues(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompTouchSensor::TouchSensor::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompTouchSensor::TouchSensor::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompTouchSensor::__patch(TouchSensorPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompTouchSensor::TouchSensorPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompTouchSensor::TouchSensor::ice_staticId(), v);
    }
}
